// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: irp.proto
#ifndef GRPC_irp_2eproto__INCLUDED
#define GRPC_irp_2eproto__INCLUDED

#include "irp.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace irp {

// gRPC 服务定义
class IrpService final {
 public:
  static constexpr char const* service_full_name() {
    return "irp.IrpService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 处理优化请求
    virtual ::grpc::Status ProcessOptimization(::grpc::ClientContext* context, const ::irp::OuReq& request, ::irp::OuResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::irp::OuResp>> AsyncProcessOptimization(::grpc::ClientContext* context, const ::irp::OuReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::irp::OuResp>>(AsyncProcessOptimizationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::irp::OuResp>> PrepareAsyncProcessOptimization(::grpc::ClientContext* context, const ::irp::OuReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::irp::OuResp>>(PrepareAsyncProcessOptimizationRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // 处理优化请求
      virtual void ProcessOptimization(::grpc::ClientContext* context, const ::irp::OuReq* request, ::irp::OuResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ProcessOptimization(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::irp::OuResp* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void ProcessOptimization(::grpc::ClientContext* context, const ::irp::OuReq* request, ::irp::OuResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void ProcessOptimization(::grpc::ClientContext* context, const ::irp::OuReq* request, ::irp::OuResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void ProcessOptimization(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::irp::OuResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void ProcessOptimization(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::irp::OuResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::irp::OuResp>* AsyncProcessOptimizationRaw(::grpc::ClientContext* context, const ::irp::OuReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::irp::OuResp>* PrepareAsyncProcessOptimizationRaw(::grpc::ClientContext* context, const ::irp::OuReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status ProcessOptimization(::grpc::ClientContext* context, const ::irp::OuReq& request, ::irp::OuResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::irp::OuResp>> AsyncProcessOptimization(::grpc::ClientContext* context, const ::irp::OuReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::irp::OuResp>>(AsyncProcessOptimizationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::irp::OuResp>> PrepareAsyncProcessOptimization(::grpc::ClientContext* context, const ::irp::OuReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::irp::OuResp>>(PrepareAsyncProcessOptimizationRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void ProcessOptimization(::grpc::ClientContext* context, const ::irp::OuReq* request, ::irp::OuResp* response, std::function<void(::grpc::Status)>) override;
      void ProcessOptimization(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::irp::OuResp* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void ProcessOptimization(::grpc::ClientContext* context, const ::irp::OuReq* request, ::irp::OuResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void ProcessOptimization(::grpc::ClientContext* context, const ::irp::OuReq* request, ::irp::OuResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void ProcessOptimization(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::irp::OuResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void ProcessOptimization(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::irp::OuResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::irp::OuResp>* AsyncProcessOptimizationRaw(::grpc::ClientContext* context, const ::irp::OuReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::irp::OuResp>* PrepareAsyncProcessOptimizationRaw(::grpc::ClientContext* context, const ::irp::OuReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ProcessOptimization_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 处理优化请求
    virtual ::grpc::Status ProcessOptimization(::grpc::ServerContext* context, const ::irp::OuReq* request, ::irp::OuResp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ProcessOptimization : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ProcessOptimization() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ProcessOptimization() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessOptimization(::grpc::ServerContext* /*context*/, const ::irp::OuReq* /*request*/, ::irp::OuResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessOptimization(::grpc::ServerContext* context, ::irp::OuReq* request, ::grpc::ServerAsyncResponseWriter< ::irp::OuResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ProcessOptimization<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_ProcessOptimization : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_ProcessOptimization() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::irp::OuReq, ::irp::OuResp>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::irp::OuReq* request, ::irp::OuResp* response) { return this->ProcessOptimization(context, request, response); }));}
    void SetMessageAllocatorFor_ProcessOptimization(
        ::grpc::experimental::MessageAllocator< ::irp::OuReq, ::irp::OuResp>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::irp::OuReq, ::irp::OuResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_ProcessOptimization() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessOptimization(::grpc::ServerContext* /*context*/, const ::irp::OuReq* /*request*/, ::irp::OuResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* ProcessOptimization(
      ::grpc::CallbackServerContext* /*context*/, const ::irp::OuReq* /*request*/, ::irp::OuResp* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* ProcessOptimization(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::irp::OuReq* /*request*/, ::irp::OuResp* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_ProcessOptimization<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_ProcessOptimization<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ProcessOptimization : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ProcessOptimization() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ProcessOptimization() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessOptimization(::grpc::ServerContext* /*context*/, const ::irp::OuReq* /*request*/, ::irp::OuResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ProcessOptimization : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ProcessOptimization() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ProcessOptimization() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessOptimization(::grpc::ServerContext* /*context*/, const ::irp::OuReq* /*request*/, ::irp::OuResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessOptimization(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_ProcessOptimization : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_ProcessOptimization() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ProcessOptimization(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_ProcessOptimization() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessOptimization(::grpc::ServerContext* /*context*/, const ::irp::OuReq* /*request*/, ::irp::OuResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* ProcessOptimization(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* ProcessOptimization(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ProcessOptimization : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ProcessOptimization() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::irp::OuReq, ::irp::OuResp>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::irp::OuReq, ::irp::OuResp>* streamer) {
                       return this->StreamedProcessOptimization(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ProcessOptimization() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ProcessOptimization(::grpc::ServerContext* /*context*/, const ::irp::OuReq* /*request*/, ::irp::OuResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedProcessOptimization(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::irp::OuReq,::irp::OuResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ProcessOptimization<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ProcessOptimization<Service > StreamedService;
};

}  // namespace irp


#endif  // GRPC_irp_2eproto__INCLUDED
