// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: irp.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_irp_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_irp_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_irp_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_irp_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_irp_2eproto;
namespace irp {
class CapaCostFunc;
class CapaCostFuncDefaultTypeInternal;
extern CapaCostFuncDefaultTypeInternal _CapaCostFunc_default_instance_;
class ControlDayOne;
class ControlDayOneDefaultTypeInternal;
extern ControlDayOneDefaultTypeInternal _ControlDayOne_default_instance_;
class OuReq;
class OuReqDefaultTypeInternal;
extern OuReqDefaultTypeInternal _OuReq_default_instance_;
class OuResp;
class OuRespDefaultTypeInternal;
extern OuRespDefaultTypeInternal _OuResp_default_instance_;
class ScenarioInfo;
class ScenarioInfoDefaultTypeInternal;
extern ScenarioInfoDefaultTypeInternal _ScenarioInfo_default_instance_;
}  // namespace irp
PROTOBUF_NAMESPACE_OPEN
template<> ::irp::CapaCostFunc* Arena::CreateMaybeMessage<::irp::CapaCostFunc>(Arena*);
template<> ::irp::ControlDayOne* Arena::CreateMaybeMessage<::irp::ControlDayOne>(Arena*);
template<> ::irp::OuReq* Arena::CreateMaybeMessage<::irp::OuReq>(Arena*);
template<> ::irp::OuResp* Arena::CreateMaybeMessage<::irp::OuResp>(Arena*);
template<> ::irp::ScenarioInfo* Arena::CreateMaybeMessage<::irp::ScenarioInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace irp {

// ===================================================================

class CapaCostFunc PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:irp.CapaCostFunc) */ {
 public:
  inline CapaCostFunc() : CapaCostFunc(nullptr) {};
  virtual ~CapaCostFunc();

  CapaCostFunc(const CapaCostFunc& from);
  CapaCostFunc(CapaCostFunc&& from) noexcept
    : CapaCostFunc() {
    *this = ::std::move(from);
  }

  inline CapaCostFunc& operator=(const CapaCostFunc& from) {
    CopyFrom(from);
    return *this;
  }
  inline CapaCostFunc& operator=(CapaCostFunc&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CapaCostFunc& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CapaCostFunc* internal_default_instance() {
    return reinterpret_cast<const CapaCostFunc*>(
               &_CapaCostFunc_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CapaCostFunc& a, CapaCostFunc& b) {
    a.Swap(&b);
  }
  inline void Swap(CapaCostFunc* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CapaCostFunc* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CapaCostFunc* New() const final {
    return CreateMaybeMessage<CapaCostFunc>(nullptr);
  }

  CapaCostFunc* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CapaCostFunc>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CapaCostFunc& from);
  void MergeFrom(const CapaCostFunc& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CapaCostFunc* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "irp.CapaCostFunc";
  }
  protected:
  explicit CapaCostFunc(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_irp_2eproto);
    return ::descriptor_table_irp_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kThresholdFieldNumber = 1,
    kCostFieldNumber = 2,
    kSlopeFieldNumber = 3,
    kInterceptFieldNumber = 4,
  };
  // double threshold = 1;
  void clear_threshold();
  double threshold() const;
  void set_threshold(double value);
  private:
  double _internal_threshold() const;
  void _internal_set_threshold(double value);
  public:

  // double cost = 2;
  void clear_cost();
  double cost() const;
  void set_cost(double value);
  private:
  double _internal_cost() const;
  void _internal_set_cost(double value);
  public:

  // double slope = 3;
  void clear_slope();
  double slope() const;
  void set_slope(double value);
  private:
  double _internal_slope() const;
  void _internal_set_slope(double value);
  public:

  // double intercept = 4;
  void clear_intercept();
  double intercept() const;
  void set_intercept(double value);
  private:
  double _internal_intercept() const;
  void _internal_set_intercept(double value);
  public:

  // @@protoc_insertion_point(class_scope:irp.CapaCostFunc)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double threshold_;
  double cost_;
  double slope_;
  double intercept_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_irp_2eproto;
};
// -------------------------------------------------------------------

class ControlDayOne PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:irp.ControlDayOne) */ {
 public:
  inline ControlDayOne() : ControlDayOne(nullptr) {};
  virtual ~ControlDayOne();

  ControlDayOne(const ControlDayOne& from);
  ControlDayOne(ControlDayOne&& from) noexcept
    : ControlDayOne() {
    *this = ::std::move(from);
  }

  inline ControlDayOne& operator=(const ControlDayOne& from) {
    CopyFrom(from);
    return *this;
  }
  inline ControlDayOne& operator=(ControlDayOne&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ControlDayOne& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ControlDayOne* internal_default_instance() {
    return reinterpret_cast<const ControlDayOne*>(
               &_ControlDayOne_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ControlDayOne& a, ControlDayOne& b) {
    a.Swap(&b);
  }
  inline void Swap(ControlDayOne* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ControlDayOne* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ControlDayOne* New() const final {
    return CreateMaybeMessage<ControlDayOne>(nullptr);
  }

  ControlDayOne* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ControlDayOne>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ControlDayOne& from);
  void MergeFrom(const ControlDayOne& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ControlDayOne* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "irp.ControlDayOne";
  }
  protected:
  explicit ControlDayOne(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_irp_2eproto);
    return ::descriptor_table_irp_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDay1CostFieldNumber = 2,
    kDay1DeliveryFieldNumber = 1,
  };
  // double day_1_cost = 2;
  void clear_day_1_cost();
  double day_1_cost() const;
  void set_day_1_cost(double value);
  private:
  double _internal_day_1_cost() const;
  void _internal_set_day_1_cost(double value);
  public:

  // bool day_1_delivery = 1;
  void clear_day_1_delivery();
  bool day_1_delivery() const;
  void set_day_1_delivery(bool value);
  private:
  bool _internal_day_1_delivery() const;
  void _internal_set_day_1_delivery(bool value);
  public:

  // @@protoc_insertion_point(class_scope:irp.ControlDayOne)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double day_1_cost_;
  bool day_1_delivery_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_irp_2eproto;
};
// -------------------------------------------------------------------

class ScenarioInfo PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:irp.ScenarioInfo) */ {
 public:
  inline ScenarioInfo() : ScenarioInfo(nullptr) {};
  virtual ~ScenarioInfo();

  ScenarioInfo(const ScenarioInfo& from);
  ScenarioInfo(ScenarioInfo&& from) noexcept
    : ScenarioInfo() {
    *this = ::std::move(from);
  }

  inline ScenarioInfo& operator=(const ScenarioInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ScenarioInfo& operator=(ScenarioInfo&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ScenarioInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ScenarioInfo* internal_default_instance() {
    return reinterpret_cast<const ScenarioInfo*>(
               &_ScenarioInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ScenarioInfo& a, ScenarioInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ScenarioInfo* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ScenarioInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ScenarioInfo* New() const final {
    return CreateMaybeMessage<ScenarioInfo>(nullptr);
  }

  ScenarioInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ScenarioInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ScenarioInfo& from);
  void MergeFrom(const ScenarioInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ScenarioInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "irp.ScenarioInfo";
  }
  protected:
  explicit ScenarioInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_irp_2eproto);
    return ::descriptor_table_irp_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDailyDemandsFieldNumber = 2,
    kDailyDeliveryCostsFieldNumber = 3,
    kDailyCapaPenaltyCostsFieldNumber = 4,
    kDailyPlansFieldNumber = 7,
    kDailyQuantitiesFieldNumber = 8,
    kDay1CostFieldNumber = 5,
    kScenarioIdFieldNumber = 1,
    kStartInventoryFieldNumber = 9,
    kTotalCostFieldNumber = 6,
  };
  // repeated double daily_demands = 2;
  int daily_demands_size() const;
  private:
  int _internal_daily_demands_size() const;
  public:
  void clear_daily_demands();
  private:
  double _internal_daily_demands(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_daily_demands() const;
  void _internal_add_daily_demands(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_daily_demands();
  public:
  double daily_demands(int index) const;
  void set_daily_demands(int index, double value);
  void add_daily_demands(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      daily_demands() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_daily_demands();

  // repeated double daily_delivery_costs = 3;
  int daily_delivery_costs_size() const;
  private:
  int _internal_daily_delivery_costs_size() const;
  public:
  void clear_daily_delivery_costs();
  private:
  double _internal_daily_delivery_costs(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_daily_delivery_costs() const;
  void _internal_add_daily_delivery_costs(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_daily_delivery_costs();
  public:
  double daily_delivery_costs(int index) const;
  void set_daily_delivery_costs(int index, double value);
  void add_daily_delivery_costs(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      daily_delivery_costs() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_daily_delivery_costs();

  // repeated .irp.CapaCostFunc daily_capa_penalty_costs = 4;
  int daily_capa_penalty_costs_size() const;
  private:
  int _internal_daily_capa_penalty_costs_size() const;
  public:
  void clear_daily_capa_penalty_costs();
  ::irp::CapaCostFunc* mutable_daily_capa_penalty_costs(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::irp::CapaCostFunc >*
      mutable_daily_capa_penalty_costs();
  private:
  const ::irp::CapaCostFunc& _internal_daily_capa_penalty_costs(int index) const;
  ::irp::CapaCostFunc* _internal_add_daily_capa_penalty_costs();
  public:
  const ::irp::CapaCostFunc& daily_capa_penalty_costs(int index) const;
  ::irp::CapaCostFunc* add_daily_capa_penalty_costs();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::irp::CapaCostFunc >&
      daily_capa_penalty_costs() const;

  // repeated bool daily_plans = 7;
  int daily_plans_size() const;
  private:
  int _internal_daily_plans_size() const;
  public:
  void clear_daily_plans();
  private:
  bool _internal_daily_plans(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >&
      _internal_daily_plans() const;
  void _internal_add_daily_plans(bool value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >*
      _internal_mutable_daily_plans();
  public:
  bool daily_plans(int index) const;
  void set_daily_plans(int index, bool value);
  void add_daily_plans(bool value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >&
      daily_plans() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >*
      mutable_daily_plans();

  // repeated double daily_quantities = 8;
  int daily_quantities_size() const;
  private:
  int _internal_daily_quantities_size() const;
  public:
  void clear_daily_quantities();
  private:
  double _internal_daily_quantities(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_daily_quantities() const;
  void _internal_add_daily_quantities(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_daily_quantities();
  public:
  double daily_quantities(int index) const;
  void set_daily_quantities(int index, double value);
  void add_daily_quantities(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      daily_quantities() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_daily_quantities();

  // double day_1_cost = 5;
  void clear_day_1_cost();
  double day_1_cost() const;
  void set_day_1_cost(double value);
  private:
  double _internal_day_1_cost() const;
  void _internal_set_day_1_cost(double value);
  public:

  // int32 scenario_id = 1;
  void clear_scenario_id();
  ::PROTOBUF_NAMESPACE_ID::int32 scenario_id() const;
  void set_scenario_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_scenario_id() const;
  void _internal_set_scenario_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 start_inventory = 9;
  bool has_start_inventory() const;
  private:
  bool _internal_has_start_inventory() const;
  public:
  void clear_start_inventory();
  ::PROTOBUF_NAMESPACE_ID::int32 start_inventory() const;
  void set_start_inventory(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_start_inventory() const;
  void _internal_set_start_inventory(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // double total_cost = 6;
  void clear_total_cost();
  double total_cost() const;
  void set_total_cost(double value);
  private:
  double _internal_total_cost() const;
  void _internal_set_total_cost(double value);
  public:

  // @@protoc_insertion_point(class_scope:irp.ScenarioInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > daily_demands_;
  mutable std::atomic<int> _daily_demands_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > daily_delivery_costs_;
  mutable std::atomic<int> _daily_delivery_costs_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::irp::CapaCostFunc > daily_capa_penalty_costs_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool > daily_plans_;
  mutable std::atomic<int> _daily_plans_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > daily_quantities_;
  mutable std::atomic<int> _daily_quantities_cached_byte_size_;
  double day_1_cost_;
  ::PROTOBUF_NAMESPACE_ID::int32 scenario_id_;
  ::PROTOBUF_NAMESPACE_ID::int32 start_inventory_;
  double total_cost_;
  friend struct ::TableStruct_irp_2eproto;
};
// -------------------------------------------------------------------

class OuReq PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:irp.OuReq) */ {
 public:
  inline OuReq() : OuReq(nullptr) {};
  virtual ~OuReq();

  OuReq(const OuReq& from);
  OuReq(OuReq&& from) noexcept
    : OuReq() {
    *this = ::std::move(from);
  }

  inline OuReq& operator=(const OuReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline OuReq& operator=(OuReq&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const OuReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OuReq* internal_default_instance() {
    return reinterpret_cast<const OuReq*>(
               &_OuReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(OuReq& a, OuReq& b) {
    a.Swap(&b);
  }
  inline void Swap(OuReq* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OuReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline OuReq* New() const final {
    return CreateMaybeMessage<OuReq>(nullptr);
  }

  OuReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<OuReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const OuReq& from);
  void MergeFrom(const OuReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OuReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "irp.OuReq";
  }
  protected:
  explicit OuReq(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_irp_2eproto);
    return ::descriptor_table_irp_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kScenarioInfosFieldNumber = 11,
    kControlDay1InfoFieldNumber = 10,
    kClientIdFieldNumber = 1,
    kNbDaysFieldNumber = 2,
    kNbScenarioFieldNumber = 3,
    kMaxInventoryFieldNumber = 4,
    kInventoryCostFieldNumber = 6,
    kStockoutCostFieldNumber = 7,
    kStartInventoryFieldNumber = 5,
    kControlDay1FieldNumber = 9,
    kSupplierMinusCostFieldNumber = 8,
  };
  // repeated .irp.ScenarioInfo scenario_infos = 11;
  int scenario_infos_size() const;
  private:
  int _internal_scenario_infos_size() const;
  public:
  void clear_scenario_infos();
  ::irp::ScenarioInfo* mutable_scenario_infos(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::irp::ScenarioInfo >*
      mutable_scenario_infos();
  private:
  const ::irp::ScenarioInfo& _internal_scenario_infos(int index) const;
  ::irp::ScenarioInfo* _internal_add_scenario_infos();
  public:
  const ::irp::ScenarioInfo& scenario_infos(int index) const;
  ::irp::ScenarioInfo* add_scenario_infos();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::irp::ScenarioInfo >&
      scenario_infos() const;

  // .irp.ControlDayOne control_day_1_info = 10;
  bool has_control_day_1_info() const;
  private:
  bool _internal_has_control_day_1_info() const;
  public:
  void clear_control_day_1_info();
  const ::irp::ControlDayOne& control_day_1_info() const;
  ::irp::ControlDayOne* release_control_day_1_info();
  ::irp::ControlDayOne* mutable_control_day_1_info();
  void set_allocated_control_day_1_info(::irp::ControlDayOne* control_day_1_info);
  private:
  const ::irp::ControlDayOne& _internal_control_day_1_info() const;
  ::irp::ControlDayOne* _internal_mutable_control_day_1_info();
  public:
  void unsafe_arena_set_allocated_control_day_1_info(
      ::irp::ControlDayOne* control_day_1_info);
  ::irp::ControlDayOne* unsafe_arena_release_control_day_1_info();

  // int32 client_id = 1;
  void clear_client_id();
  ::PROTOBUF_NAMESPACE_ID::int32 client_id() const;
  void set_client_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_client_id() const;
  void _internal_set_client_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 nb_days = 2;
  void clear_nb_days();
  ::PROTOBUF_NAMESPACE_ID::int32 nb_days() const;
  void set_nb_days(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_nb_days() const;
  void _internal_set_nb_days(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 nb_scenario = 3;
  void clear_nb_scenario();
  ::PROTOBUF_NAMESPACE_ID::int32 nb_scenario() const;
  void set_nb_scenario(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_nb_scenario() const;
  void _internal_set_nb_scenario(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 max_inventory = 4;
  void clear_max_inventory();
  ::PROTOBUF_NAMESPACE_ID::int32 max_inventory() const;
  void set_max_inventory(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_max_inventory() const;
  void _internal_set_max_inventory(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // double inventory_cost = 6;
  void clear_inventory_cost();
  double inventory_cost() const;
  void set_inventory_cost(double value);
  private:
  double _internal_inventory_cost() const;
  void _internal_set_inventory_cost(double value);
  public:

  // double stockout_cost = 7;
  void clear_stockout_cost();
  double stockout_cost() const;
  void set_stockout_cost(double value);
  private:
  double _internal_stockout_cost() const;
  void _internal_set_stockout_cost(double value);
  public:

  // int32 start_inventory = 5;
  void clear_start_inventory();
  ::PROTOBUF_NAMESPACE_ID::int32 start_inventory() const;
  void set_start_inventory(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_start_inventory() const;
  void _internal_set_start_inventory(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 control_day_1 = 9;
  void clear_control_day_1();
  ::PROTOBUF_NAMESPACE_ID::int32 control_day_1() const;
  void set_control_day_1(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_control_day_1() const;
  void _internal_set_control_day_1(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // double supplier_minus_cost = 8;
  void clear_supplier_minus_cost();
  double supplier_minus_cost() const;
  void set_supplier_minus_cost(double value);
  private:
  double _internal_supplier_minus_cost() const;
  void _internal_set_supplier_minus_cost(double value);
  public:

  // @@protoc_insertion_point(class_scope:irp.OuReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::irp::ScenarioInfo > scenario_infos_;
  ::irp::ControlDayOne* control_day_1_info_;
  ::PROTOBUF_NAMESPACE_ID::int32 client_id_;
  ::PROTOBUF_NAMESPACE_ID::int32 nb_days_;
  ::PROTOBUF_NAMESPACE_ID::int32 nb_scenario_;
  ::PROTOBUF_NAMESPACE_ID::int32 max_inventory_;
  double inventory_cost_;
  double stockout_cost_;
  ::PROTOBUF_NAMESPACE_ID::int32 start_inventory_;
  ::PROTOBUF_NAMESPACE_ID::int32 control_day_1_;
  double supplier_minus_cost_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_irp_2eproto;
};
// -------------------------------------------------------------------

class OuResp PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:irp.OuResp) */ {
 public:
  inline OuResp() : OuResp(nullptr) {};
  virtual ~OuResp();

  OuResp(const OuResp& from);
  OuResp(OuResp&& from) noexcept
    : OuResp() {
    *this = ::std::move(from);
  }

  inline OuResp& operator=(const OuResp& from) {
    CopyFrom(from);
    return *this;
  }
  inline OuResp& operator=(OuResp&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const OuResp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OuResp* internal_default_instance() {
    return reinterpret_cast<const OuResp*>(
               &_OuResp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(OuResp& a, OuResp& b) {
    a.Swap(&b);
  }
  inline void Swap(OuResp* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OuResp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline OuResp* New() const final {
    return CreateMaybeMessage<OuResp>(nullptr);
  }

  OuResp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<OuResp>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const OuResp& from);
  void MergeFrom(const OuResp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OuResp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "irp.OuResp";
  }
  protected:
  explicit OuResp(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_irp_2eproto);
    return ::descriptor_table_irp_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kScenarioInfoResultsFieldNumber = 1,
  };
  // repeated .irp.ScenarioInfo scenario_info_results = 1;
  int scenario_info_results_size() const;
  private:
  int _internal_scenario_info_results_size() const;
  public:
  void clear_scenario_info_results();
  ::irp::ScenarioInfo* mutable_scenario_info_results(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::irp::ScenarioInfo >*
      mutable_scenario_info_results();
  private:
  const ::irp::ScenarioInfo& _internal_scenario_info_results(int index) const;
  ::irp::ScenarioInfo* _internal_add_scenario_info_results();
  public:
  const ::irp::ScenarioInfo& scenario_info_results(int index) const;
  ::irp::ScenarioInfo* add_scenario_info_results();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::irp::ScenarioInfo >&
      scenario_info_results() const;

  // @@protoc_insertion_point(class_scope:irp.OuResp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::irp::ScenarioInfo > scenario_info_results_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_irp_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CapaCostFunc

// double threshold = 1;
inline void CapaCostFunc::clear_threshold() {
  threshold_ = 0;
}
inline double CapaCostFunc::_internal_threshold() const {
  return threshold_;
}
inline double CapaCostFunc::threshold() const {
  // @@protoc_insertion_point(field_get:irp.CapaCostFunc.threshold)
  return _internal_threshold();
}
inline void CapaCostFunc::_internal_set_threshold(double value) {
  
  threshold_ = value;
}
inline void CapaCostFunc::set_threshold(double value) {
  _internal_set_threshold(value);
  // @@protoc_insertion_point(field_set:irp.CapaCostFunc.threshold)
}

// double cost = 2;
inline void CapaCostFunc::clear_cost() {
  cost_ = 0;
}
inline double CapaCostFunc::_internal_cost() const {
  return cost_;
}
inline double CapaCostFunc::cost() const {
  // @@protoc_insertion_point(field_get:irp.CapaCostFunc.cost)
  return _internal_cost();
}
inline void CapaCostFunc::_internal_set_cost(double value) {
  
  cost_ = value;
}
inline void CapaCostFunc::set_cost(double value) {
  _internal_set_cost(value);
  // @@protoc_insertion_point(field_set:irp.CapaCostFunc.cost)
}

// double slope = 3;
inline void CapaCostFunc::clear_slope() {
  slope_ = 0;
}
inline double CapaCostFunc::_internal_slope() const {
  return slope_;
}
inline double CapaCostFunc::slope() const {
  // @@protoc_insertion_point(field_get:irp.CapaCostFunc.slope)
  return _internal_slope();
}
inline void CapaCostFunc::_internal_set_slope(double value) {
  
  slope_ = value;
}
inline void CapaCostFunc::set_slope(double value) {
  _internal_set_slope(value);
  // @@protoc_insertion_point(field_set:irp.CapaCostFunc.slope)
}

// double intercept = 4;
inline void CapaCostFunc::clear_intercept() {
  intercept_ = 0;
}
inline double CapaCostFunc::_internal_intercept() const {
  return intercept_;
}
inline double CapaCostFunc::intercept() const {
  // @@protoc_insertion_point(field_get:irp.CapaCostFunc.intercept)
  return _internal_intercept();
}
inline void CapaCostFunc::_internal_set_intercept(double value) {
  
  intercept_ = value;
}
inline void CapaCostFunc::set_intercept(double value) {
  _internal_set_intercept(value);
  // @@protoc_insertion_point(field_set:irp.CapaCostFunc.intercept)
}

// -------------------------------------------------------------------

// ControlDayOne

// bool day_1_delivery = 1;
inline void ControlDayOne::clear_day_1_delivery() {
  day_1_delivery_ = false;
}
inline bool ControlDayOne::_internal_day_1_delivery() const {
  return day_1_delivery_;
}
inline bool ControlDayOne::day_1_delivery() const {
  // @@protoc_insertion_point(field_get:irp.ControlDayOne.day_1_delivery)
  return _internal_day_1_delivery();
}
inline void ControlDayOne::_internal_set_day_1_delivery(bool value) {
  
  day_1_delivery_ = value;
}
inline void ControlDayOne::set_day_1_delivery(bool value) {
  _internal_set_day_1_delivery(value);
  // @@protoc_insertion_point(field_set:irp.ControlDayOne.day_1_delivery)
}

// double day_1_cost = 2;
inline void ControlDayOne::clear_day_1_cost() {
  day_1_cost_ = 0;
}
inline double ControlDayOne::_internal_day_1_cost() const {
  return day_1_cost_;
}
inline double ControlDayOne::day_1_cost() const {
  // @@protoc_insertion_point(field_get:irp.ControlDayOne.day_1_cost)
  return _internal_day_1_cost();
}
inline void ControlDayOne::_internal_set_day_1_cost(double value) {
  
  day_1_cost_ = value;
}
inline void ControlDayOne::set_day_1_cost(double value) {
  _internal_set_day_1_cost(value);
  // @@protoc_insertion_point(field_set:irp.ControlDayOne.day_1_cost)
}

// -------------------------------------------------------------------

// ScenarioInfo

// int32 scenario_id = 1;
inline void ScenarioInfo::clear_scenario_id() {
  scenario_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ScenarioInfo::_internal_scenario_id() const {
  return scenario_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ScenarioInfo::scenario_id() const {
  // @@protoc_insertion_point(field_get:irp.ScenarioInfo.scenario_id)
  return _internal_scenario_id();
}
inline void ScenarioInfo::_internal_set_scenario_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  scenario_id_ = value;
}
inline void ScenarioInfo::set_scenario_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_scenario_id(value);
  // @@protoc_insertion_point(field_set:irp.ScenarioInfo.scenario_id)
}

// repeated double daily_demands = 2;
inline int ScenarioInfo::_internal_daily_demands_size() const {
  return daily_demands_.size();
}
inline int ScenarioInfo::daily_demands_size() const {
  return _internal_daily_demands_size();
}
inline void ScenarioInfo::clear_daily_demands() {
  daily_demands_.Clear();
}
inline double ScenarioInfo::_internal_daily_demands(int index) const {
  return daily_demands_.Get(index);
}
inline double ScenarioInfo::daily_demands(int index) const {
  // @@protoc_insertion_point(field_get:irp.ScenarioInfo.daily_demands)
  return _internal_daily_demands(index);
}
inline void ScenarioInfo::set_daily_demands(int index, double value) {
  daily_demands_.Set(index, value);
  // @@protoc_insertion_point(field_set:irp.ScenarioInfo.daily_demands)
}
inline void ScenarioInfo::_internal_add_daily_demands(double value) {
  daily_demands_.Add(value);
}
inline void ScenarioInfo::add_daily_demands(double value) {
  _internal_add_daily_demands(value);
  // @@protoc_insertion_point(field_add:irp.ScenarioInfo.daily_demands)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ScenarioInfo::_internal_daily_demands() const {
  return daily_demands_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ScenarioInfo::daily_demands() const {
  // @@protoc_insertion_point(field_list:irp.ScenarioInfo.daily_demands)
  return _internal_daily_demands();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ScenarioInfo::_internal_mutable_daily_demands() {
  return &daily_demands_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ScenarioInfo::mutable_daily_demands() {
  // @@protoc_insertion_point(field_mutable_list:irp.ScenarioInfo.daily_demands)
  return _internal_mutable_daily_demands();
}

// repeated double daily_delivery_costs = 3;
inline int ScenarioInfo::_internal_daily_delivery_costs_size() const {
  return daily_delivery_costs_.size();
}
inline int ScenarioInfo::daily_delivery_costs_size() const {
  return _internal_daily_delivery_costs_size();
}
inline void ScenarioInfo::clear_daily_delivery_costs() {
  daily_delivery_costs_.Clear();
}
inline double ScenarioInfo::_internal_daily_delivery_costs(int index) const {
  return daily_delivery_costs_.Get(index);
}
inline double ScenarioInfo::daily_delivery_costs(int index) const {
  // @@protoc_insertion_point(field_get:irp.ScenarioInfo.daily_delivery_costs)
  return _internal_daily_delivery_costs(index);
}
inline void ScenarioInfo::set_daily_delivery_costs(int index, double value) {
  daily_delivery_costs_.Set(index, value);
  // @@protoc_insertion_point(field_set:irp.ScenarioInfo.daily_delivery_costs)
}
inline void ScenarioInfo::_internal_add_daily_delivery_costs(double value) {
  daily_delivery_costs_.Add(value);
}
inline void ScenarioInfo::add_daily_delivery_costs(double value) {
  _internal_add_daily_delivery_costs(value);
  // @@protoc_insertion_point(field_add:irp.ScenarioInfo.daily_delivery_costs)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ScenarioInfo::_internal_daily_delivery_costs() const {
  return daily_delivery_costs_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ScenarioInfo::daily_delivery_costs() const {
  // @@protoc_insertion_point(field_list:irp.ScenarioInfo.daily_delivery_costs)
  return _internal_daily_delivery_costs();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ScenarioInfo::_internal_mutable_daily_delivery_costs() {
  return &daily_delivery_costs_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ScenarioInfo::mutable_daily_delivery_costs() {
  // @@protoc_insertion_point(field_mutable_list:irp.ScenarioInfo.daily_delivery_costs)
  return _internal_mutable_daily_delivery_costs();
}

// repeated .irp.CapaCostFunc daily_capa_penalty_costs = 4;
inline int ScenarioInfo::_internal_daily_capa_penalty_costs_size() const {
  return daily_capa_penalty_costs_.size();
}
inline int ScenarioInfo::daily_capa_penalty_costs_size() const {
  return _internal_daily_capa_penalty_costs_size();
}
inline void ScenarioInfo::clear_daily_capa_penalty_costs() {
  daily_capa_penalty_costs_.Clear();
}
inline ::irp::CapaCostFunc* ScenarioInfo::mutable_daily_capa_penalty_costs(int index) {
  // @@protoc_insertion_point(field_mutable:irp.ScenarioInfo.daily_capa_penalty_costs)
  return daily_capa_penalty_costs_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::irp::CapaCostFunc >*
ScenarioInfo::mutable_daily_capa_penalty_costs() {
  // @@protoc_insertion_point(field_mutable_list:irp.ScenarioInfo.daily_capa_penalty_costs)
  return &daily_capa_penalty_costs_;
}
inline const ::irp::CapaCostFunc& ScenarioInfo::_internal_daily_capa_penalty_costs(int index) const {
  return daily_capa_penalty_costs_.Get(index);
}
inline const ::irp::CapaCostFunc& ScenarioInfo::daily_capa_penalty_costs(int index) const {
  // @@protoc_insertion_point(field_get:irp.ScenarioInfo.daily_capa_penalty_costs)
  return _internal_daily_capa_penalty_costs(index);
}
inline ::irp::CapaCostFunc* ScenarioInfo::_internal_add_daily_capa_penalty_costs() {
  return daily_capa_penalty_costs_.Add();
}
inline ::irp::CapaCostFunc* ScenarioInfo::add_daily_capa_penalty_costs() {
  // @@protoc_insertion_point(field_add:irp.ScenarioInfo.daily_capa_penalty_costs)
  return _internal_add_daily_capa_penalty_costs();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::irp::CapaCostFunc >&
ScenarioInfo::daily_capa_penalty_costs() const {
  // @@protoc_insertion_point(field_list:irp.ScenarioInfo.daily_capa_penalty_costs)
  return daily_capa_penalty_costs_;
}

// double day_1_cost = 5;
inline void ScenarioInfo::clear_day_1_cost() {
  day_1_cost_ = 0;
}
inline double ScenarioInfo::_internal_day_1_cost() const {
  return day_1_cost_;
}
inline double ScenarioInfo::day_1_cost() const {
  // @@protoc_insertion_point(field_get:irp.ScenarioInfo.day_1_cost)
  return _internal_day_1_cost();
}
inline void ScenarioInfo::_internal_set_day_1_cost(double value) {
  
  day_1_cost_ = value;
}
inline void ScenarioInfo::set_day_1_cost(double value) {
  _internal_set_day_1_cost(value);
  // @@protoc_insertion_point(field_set:irp.ScenarioInfo.day_1_cost)
}

// double total_cost = 6;
inline void ScenarioInfo::clear_total_cost() {
  total_cost_ = 0;
}
inline double ScenarioInfo::_internal_total_cost() const {
  return total_cost_;
}
inline double ScenarioInfo::total_cost() const {
  // @@protoc_insertion_point(field_get:irp.ScenarioInfo.total_cost)
  return _internal_total_cost();
}
inline void ScenarioInfo::_internal_set_total_cost(double value) {
  
  total_cost_ = value;
}
inline void ScenarioInfo::set_total_cost(double value) {
  _internal_set_total_cost(value);
  // @@protoc_insertion_point(field_set:irp.ScenarioInfo.total_cost)
}

// repeated bool daily_plans = 7;
inline int ScenarioInfo::_internal_daily_plans_size() const {
  return daily_plans_.size();
}
inline int ScenarioInfo::daily_plans_size() const {
  return _internal_daily_plans_size();
}
inline void ScenarioInfo::clear_daily_plans() {
  daily_plans_.Clear();
}
inline bool ScenarioInfo::_internal_daily_plans(int index) const {
  return daily_plans_.Get(index);
}
inline bool ScenarioInfo::daily_plans(int index) const {
  // @@protoc_insertion_point(field_get:irp.ScenarioInfo.daily_plans)
  return _internal_daily_plans(index);
}
inline void ScenarioInfo::set_daily_plans(int index, bool value) {
  daily_plans_.Set(index, value);
  // @@protoc_insertion_point(field_set:irp.ScenarioInfo.daily_plans)
}
inline void ScenarioInfo::_internal_add_daily_plans(bool value) {
  daily_plans_.Add(value);
}
inline void ScenarioInfo::add_daily_plans(bool value) {
  _internal_add_daily_plans(value);
  // @@protoc_insertion_point(field_add:irp.ScenarioInfo.daily_plans)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >&
ScenarioInfo::_internal_daily_plans() const {
  return daily_plans_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >&
ScenarioInfo::daily_plans() const {
  // @@protoc_insertion_point(field_list:irp.ScenarioInfo.daily_plans)
  return _internal_daily_plans();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >*
ScenarioInfo::_internal_mutable_daily_plans() {
  return &daily_plans_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >*
ScenarioInfo::mutable_daily_plans() {
  // @@protoc_insertion_point(field_mutable_list:irp.ScenarioInfo.daily_plans)
  return _internal_mutable_daily_plans();
}

// repeated double daily_quantities = 8;
inline int ScenarioInfo::_internal_daily_quantities_size() const {
  return daily_quantities_.size();
}
inline int ScenarioInfo::daily_quantities_size() const {
  return _internal_daily_quantities_size();
}
inline void ScenarioInfo::clear_daily_quantities() {
  daily_quantities_.Clear();
}
inline double ScenarioInfo::_internal_daily_quantities(int index) const {
  return daily_quantities_.Get(index);
}
inline double ScenarioInfo::daily_quantities(int index) const {
  // @@protoc_insertion_point(field_get:irp.ScenarioInfo.daily_quantities)
  return _internal_daily_quantities(index);
}
inline void ScenarioInfo::set_daily_quantities(int index, double value) {
  daily_quantities_.Set(index, value);
  // @@protoc_insertion_point(field_set:irp.ScenarioInfo.daily_quantities)
}
inline void ScenarioInfo::_internal_add_daily_quantities(double value) {
  daily_quantities_.Add(value);
}
inline void ScenarioInfo::add_daily_quantities(double value) {
  _internal_add_daily_quantities(value);
  // @@protoc_insertion_point(field_add:irp.ScenarioInfo.daily_quantities)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ScenarioInfo::_internal_daily_quantities() const {
  return daily_quantities_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ScenarioInfo::daily_quantities() const {
  // @@protoc_insertion_point(field_list:irp.ScenarioInfo.daily_quantities)
  return _internal_daily_quantities();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ScenarioInfo::_internal_mutable_daily_quantities() {
  return &daily_quantities_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ScenarioInfo::mutable_daily_quantities() {
  // @@protoc_insertion_point(field_mutable_list:irp.ScenarioInfo.daily_quantities)
  return _internal_mutable_daily_quantities();
}

// int32 start_inventory = 9;
inline bool ScenarioInfo::_internal_has_start_inventory() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ScenarioInfo::has_start_inventory() const {
  return _internal_has_start_inventory();
}
inline void ScenarioInfo::clear_start_inventory() {
  start_inventory_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ScenarioInfo::_internal_start_inventory() const {
  return start_inventory_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ScenarioInfo::start_inventory() const {
  // @@protoc_insertion_point(field_get:irp.ScenarioInfo.start_inventory)
  return _internal_start_inventory();
}
inline void ScenarioInfo::_internal_set_start_inventory(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  start_inventory_ = value;
}
inline void ScenarioInfo::set_start_inventory(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_start_inventory(value);
  // @@protoc_insertion_point(field_set:irp.ScenarioInfo.start_inventory)
}

// -------------------------------------------------------------------

// OuReq

// int32 client_id = 1;
inline void OuReq::clear_client_id() {
  client_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OuReq::_internal_client_id() const {
  return client_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OuReq::client_id() const {
  // @@protoc_insertion_point(field_get:irp.OuReq.client_id)
  return _internal_client_id();
}
inline void OuReq::_internal_set_client_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  client_id_ = value;
}
inline void OuReq::set_client_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_client_id(value);
  // @@protoc_insertion_point(field_set:irp.OuReq.client_id)
}

// int32 nb_days = 2;
inline void OuReq::clear_nb_days() {
  nb_days_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OuReq::_internal_nb_days() const {
  return nb_days_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OuReq::nb_days() const {
  // @@protoc_insertion_point(field_get:irp.OuReq.nb_days)
  return _internal_nb_days();
}
inline void OuReq::_internal_set_nb_days(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  nb_days_ = value;
}
inline void OuReq::set_nb_days(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_nb_days(value);
  // @@protoc_insertion_point(field_set:irp.OuReq.nb_days)
}

// int32 nb_scenario = 3;
inline void OuReq::clear_nb_scenario() {
  nb_scenario_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OuReq::_internal_nb_scenario() const {
  return nb_scenario_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OuReq::nb_scenario() const {
  // @@protoc_insertion_point(field_get:irp.OuReq.nb_scenario)
  return _internal_nb_scenario();
}
inline void OuReq::_internal_set_nb_scenario(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  nb_scenario_ = value;
}
inline void OuReq::set_nb_scenario(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_nb_scenario(value);
  // @@protoc_insertion_point(field_set:irp.OuReq.nb_scenario)
}

// int32 max_inventory = 4;
inline void OuReq::clear_max_inventory() {
  max_inventory_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OuReq::_internal_max_inventory() const {
  return max_inventory_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OuReq::max_inventory() const {
  // @@protoc_insertion_point(field_get:irp.OuReq.max_inventory)
  return _internal_max_inventory();
}
inline void OuReq::_internal_set_max_inventory(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  max_inventory_ = value;
}
inline void OuReq::set_max_inventory(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_max_inventory(value);
  // @@protoc_insertion_point(field_set:irp.OuReq.max_inventory)
}

// int32 start_inventory = 5;
inline void OuReq::clear_start_inventory() {
  start_inventory_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OuReq::_internal_start_inventory() const {
  return start_inventory_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OuReq::start_inventory() const {
  // @@protoc_insertion_point(field_get:irp.OuReq.start_inventory)
  return _internal_start_inventory();
}
inline void OuReq::_internal_set_start_inventory(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  start_inventory_ = value;
}
inline void OuReq::set_start_inventory(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_start_inventory(value);
  // @@protoc_insertion_point(field_set:irp.OuReq.start_inventory)
}

// double inventory_cost = 6;
inline void OuReq::clear_inventory_cost() {
  inventory_cost_ = 0;
}
inline double OuReq::_internal_inventory_cost() const {
  return inventory_cost_;
}
inline double OuReq::inventory_cost() const {
  // @@protoc_insertion_point(field_get:irp.OuReq.inventory_cost)
  return _internal_inventory_cost();
}
inline void OuReq::_internal_set_inventory_cost(double value) {
  
  inventory_cost_ = value;
}
inline void OuReq::set_inventory_cost(double value) {
  _internal_set_inventory_cost(value);
  // @@protoc_insertion_point(field_set:irp.OuReq.inventory_cost)
}

// double stockout_cost = 7;
inline void OuReq::clear_stockout_cost() {
  stockout_cost_ = 0;
}
inline double OuReq::_internal_stockout_cost() const {
  return stockout_cost_;
}
inline double OuReq::stockout_cost() const {
  // @@protoc_insertion_point(field_get:irp.OuReq.stockout_cost)
  return _internal_stockout_cost();
}
inline void OuReq::_internal_set_stockout_cost(double value) {
  
  stockout_cost_ = value;
}
inline void OuReq::set_stockout_cost(double value) {
  _internal_set_stockout_cost(value);
  // @@protoc_insertion_point(field_set:irp.OuReq.stockout_cost)
}

// double supplier_minus_cost = 8;
inline void OuReq::clear_supplier_minus_cost() {
  supplier_minus_cost_ = 0;
}
inline double OuReq::_internal_supplier_minus_cost() const {
  return supplier_minus_cost_;
}
inline double OuReq::supplier_minus_cost() const {
  // @@protoc_insertion_point(field_get:irp.OuReq.supplier_minus_cost)
  return _internal_supplier_minus_cost();
}
inline void OuReq::_internal_set_supplier_minus_cost(double value) {
  
  supplier_minus_cost_ = value;
}
inline void OuReq::set_supplier_minus_cost(double value) {
  _internal_set_supplier_minus_cost(value);
  // @@protoc_insertion_point(field_set:irp.OuReq.supplier_minus_cost)
}

// int32 control_day_1 = 9;
inline void OuReq::clear_control_day_1() {
  control_day_1_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OuReq::_internal_control_day_1() const {
  return control_day_1_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OuReq::control_day_1() const {
  // @@protoc_insertion_point(field_get:irp.OuReq.control_day_1)
  return _internal_control_day_1();
}
inline void OuReq::_internal_set_control_day_1(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  control_day_1_ = value;
}
inline void OuReq::set_control_day_1(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_control_day_1(value);
  // @@protoc_insertion_point(field_set:irp.OuReq.control_day_1)
}

// .irp.ControlDayOne control_day_1_info = 10;
inline bool OuReq::_internal_has_control_day_1_info() const {
  return this != internal_default_instance() && control_day_1_info_ != nullptr;
}
inline bool OuReq::has_control_day_1_info() const {
  return _internal_has_control_day_1_info();
}
inline void OuReq::clear_control_day_1_info() {
  if (GetArena() == nullptr && control_day_1_info_ != nullptr) {
    delete control_day_1_info_;
  }
  control_day_1_info_ = nullptr;
}
inline const ::irp::ControlDayOne& OuReq::_internal_control_day_1_info() const {
  const ::irp::ControlDayOne* p = control_day_1_info_;
  return p != nullptr ? *p : *reinterpret_cast<const ::irp::ControlDayOne*>(
      &::irp::_ControlDayOne_default_instance_);
}
inline const ::irp::ControlDayOne& OuReq::control_day_1_info() const {
  // @@protoc_insertion_point(field_get:irp.OuReq.control_day_1_info)
  return _internal_control_day_1_info();
}
inline void OuReq::unsafe_arena_set_allocated_control_day_1_info(
    ::irp::ControlDayOne* control_day_1_info) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(control_day_1_info_);
  }
  control_day_1_info_ = control_day_1_info;
  if (control_day_1_info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:irp.OuReq.control_day_1_info)
}
inline ::irp::ControlDayOne* OuReq::release_control_day_1_info() {
  auto temp = unsafe_arena_release_control_day_1_info();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::irp::ControlDayOne* OuReq::unsafe_arena_release_control_day_1_info() {
  // @@protoc_insertion_point(field_release:irp.OuReq.control_day_1_info)
  
  ::irp::ControlDayOne* temp = control_day_1_info_;
  control_day_1_info_ = nullptr;
  return temp;
}
inline ::irp::ControlDayOne* OuReq::_internal_mutable_control_day_1_info() {
  
  if (control_day_1_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::irp::ControlDayOne>(GetArena());
    control_day_1_info_ = p;
  }
  return control_day_1_info_;
}
inline ::irp::ControlDayOne* OuReq::mutable_control_day_1_info() {
  // @@protoc_insertion_point(field_mutable:irp.OuReq.control_day_1_info)
  return _internal_mutable_control_day_1_info();
}
inline void OuReq::set_allocated_control_day_1_info(::irp::ControlDayOne* control_day_1_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete control_day_1_info_;
  }
  if (control_day_1_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(control_day_1_info);
    if (message_arena != submessage_arena) {
      control_day_1_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, control_day_1_info, submessage_arena);
    }
    
  } else {
    
  }
  control_day_1_info_ = control_day_1_info;
  // @@protoc_insertion_point(field_set_allocated:irp.OuReq.control_day_1_info)
}

// repeated .irp.ScenarioInfo scenario_infos = 11;
inline int OuReq::_internal_scenario_infos_size() const {
  return scenario_infos_.size();
}
inline int OuReq::scenario_infos_size() const {
  return _internal_scenario_infos_size();
}
inline void OuReq::clear_scenario_infos() {
  scenario_infos_.Clear();
}
inline ::irp::ScenarioInfo* OuReq::mutable_scenario_infos(int index) {
  // @@protoc_insertion_point(field_mutable:irp.OuReq.scenario_infos)
  return scenario_infos_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::irp::ScenarioInfo >*
OuReq::mutable_scenario_infos() {
  // @@protoc_insertion_point(field_mutable_list:irp.OuReq.scenario_infos)
  return &scenario_infos_;
}
inline const ::irp::ScenarioInfo& OuReq::_internal_scenario_infos(int index) const {
  return scenario_infos_.Get(index);
}
inline const ::irp::ScenarioInfo& OuReq::scenario_infos(int index) const {
  // @@protoc_insertion_point(field_get:irp.OuReq.scenario_infos)
  return _internal_scenario_infos(index);
}
inline ::irp::ScenarioInfo* OuReq::_internal_add_scenario_infos() {
  return scenario_infos_.Add();
}
inline ::irp::ScenarioInfo* OuReq::add_scenario_infos() {
  // @@protoc_insertion_point(field_add:irp.OuReq.scenario_infos)
  return _internal_add_scenario_infos();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::irp::ScenarioInfo >&
OuReq::scenario_infos() const {
  // @@protoc_insertion_point(field_list:irp.OuReq.scenario_infos)
  return scenario_infos_;
}

// -------------------------------------------------------------------

// OuResp

// repeated .irp.ScenarioInfo scenario_info_results = 1;
inline int OuResp::_internal_scenario_info_results_size() const {
  return scenario_info_results_.size();
}
inline int OuResp::scenario_info_results_size() const {
  return _internal_scenario_info_results_size();
}
inline void OuResp::clear_scenario_info_results() {
  scenario_info_results_.Clear();
}
inline ::irp::ScenarioInfo* OuResp::mutable_scenario_info_results(int index) {
  // @@protoc_insertion_point(field_mutable:irp.OuResp.scenario_info_results)
  return scenario_info_results_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::irp::ScenarioInfo >*
OuResp::mutable_scenario_info_results() {
  // @@protoc_insertion_point(field_mutable_list:irp.OuResp.scenario_info_results)
  return &scenario_info_results_;
}
inline const ::irp::ScenarioInfo& OuResp::_internal_scenario_info_results(int index) const {
  return scenario_info_results_.Get(index);
}
inline const ::irp::ScenarioInfo& OuResp::scenario_info_results(int index) const {
  // @@protoc_insertion_point(field_get:irp.OuResp.scenario_info_results)
  return _internal_scenario_info_results(index);
}
inline ::irp::ScenarioInfo* OuResp::_internal_add_scenario_info_results() {
  return scenario_info_results_.Add();
}
inline ::irp::ScenarioInfo* OuResp::add_scenario_info_results() {
  // @@protoc_insertion_point(field_add:irp.OuResp.scenario_info_results)
  return _internal_add_scenario_info_results();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::irp::ScenarioInfo >&
OuResp::scenario_info_results() const {
  // @@protoc_insertion_point(field_list:irp.OuResp.scenario_info_results)
  return scenario_info_results_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace irp

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_irp_2eproto
