// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: irp.proto

#include "irp.pb.h"
#include "irp.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace irp {

static const char* IrpService_method_names[] = {
  "/irp.IrpService/ProcessOptimization",
};

std::unique_ptr< IrpService::Stub> IrpService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< IrpService::Stub> stub(new IrpService::Stub(channel));
  return stub;
}

IrpService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_ProcessOptimization_(IrpService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status IrpService::Stub::ProcessOptimization(::grpc::ClientContext* context, const ::irp::OuReq& request, ::irp::OuResp* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ProcessOptimization_, context, request, response);
}

void IrpService::Stub::experimental_async::ProcessOptimization(::grpc::ClientContext* context, const ::irp::OuReq* request, ::irp::OuResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ProcessOptimization_, context, request, response, std::move(f));
}

void IrpService::Stub::experimental_async::ProcessOptimization(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::irp::OuResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ProcessOptimization_, context, request, response, std::move(f));
}

void IrpService::Stub::experimental_async::ProcessOptimization(::grpc::ClientContext* context, const ::irp::OuReq* request, ::irp::OuResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ProcessOptimization_, context, request, response, reactor);
}

void IrpService::Stub::experimental_async::ProcessOptimization(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::irp::OuResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ProcessOptimization_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::irp::OuResp>* IrpService::Stub::AsyncProcessOptimizationRaw(::grpc::ClientContext* context, const ::irp::OuReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::irp::OuResp>::Create(channel_.get(), cq, rpcmethod_ProcessOptimization_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::irp::OuResp>* IrpService::Stub::PrepareAsyncProcessOptimizationRaw(::grpc::ClientContext* context, const ::irp::OuReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::irp::OuResp>::Create(channel_.get(), cq, rpcmethod_ProcessOptimization_, context, request, false);
}

IrpService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      IrpService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< IrpService::Service, ::irp::OuReq, ::irp::OuResp>(
          [](IrpService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::irp::OuReq* req,
             ::irp::OuResp* resp) {
               return service->ProcessOptimization(ctx, req, resp);
             }, this)));
}

IrpService::Service::~Service() {
}

::grpc::Status IrpService::Service::ProcessOptimization(::grpc::ServerContext* context, const ::irp::OuReq* request, ::irp::OuResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace irp

