// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: irp.proto

#include "irp.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_irp_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_CapaCostFunc_irp_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_irp_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ControlDayOne_irp_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_irp_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ScenarioInfo_irp_2eproto;
namespace irp {
class CapaCostFuncDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<CapaCostFunc> _instance;
} _CapaCostFunc_default_instance_;
class ControlDayOneDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ControlDayOne> _instance;
} _ControlDayOne_default_instance_;
class ScenarioInfoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ScenarioInfo> _instance;
} _ScenarioInfo_default_instance_;
class OuReqDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<OuReq> _instance;
} _OuReq_default_instance_;
class OuRespDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<OuResp> _instance;
} _OuResp_default_instance_;
}  // namespace irp
static void InitDefaultsscc_info_CapaCostFunc_irp_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::irp::_CapaCostFunc_default_instance_;
    new (ptr) ::irp::CapaCostFunc();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::irp::CapaCostFunc::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_CapaCostFunc_irp_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_CapaCostFunc_irp_2eproto}, {}};

static void InitDefaultsscc_info_ControlDayOne_irp_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::irp::_ControlDayOne_default_instance_;
    new (ptr) ::irp::ControlDayOne();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::irp::ControlDayOne::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ControlDayOne_irp_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ControlDayOne_irp_2eproto}, {}};

static void InitDefaultsscc_info_OuReq_irp_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::irp::_OuReq_default_instance_;
    new (ptr) ::irp::OuReq();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::irp::OuReq::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_OuReq_irp_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_OuReq_irp_2eproto}, {
      &scc_info_ControlDayOne_irp_2eproto.base,
      &scc_info_ScenarioInfo_irp_2eproto.base,}};

static void InitDefaultsscc_info_OuResp_irp_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::irp::_OuResp_default_instance_;
    new (ptr) ::irp::OuResp();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::irp::OuResp::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_OuResp_irp_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_OuResp_irp_2eproto}, {
      &scc_info_ScenarioInfo_irp_2eproto.base,}};

static void InitDefaultsscc_info_ScenarioInfo_irp_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::irp::_ScenarioInfo_default_instance_;
    new (ptr) ::irp::ScenarioInfo();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::irp::ScenarioInfo::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ScenarioInfo_irp_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_ScenarioInfo_irp_2eproto}, {
      &scc_info_CapaCostFunc_irp_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_irp_2eproto[5];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_irp_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_irp_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_irp_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::irp::CapaCostFunc, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::irp::CapaCostFunc, threshold_),
  PROTOBUF_FIELD_OFFSET(::irp::CapaCostFunc, cost_),
  PROTOBUF_FIELD_OFFSET(::irp::CapaCostFunc, slope_),
  PROTOBUF_FIELD_OFFSET(::irp::CapaCostFunc, intercept_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::irp::ControlDayOne, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::irp::ControlDayOne, day_1_delivery_),
  PROTOBUF_FIELD_OFFSET(::irp::ControlDayOne, day_1_cost_),
  PROTOBUF_FIELD_OFFSET(::irp::ScenarioInfo, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::irp::ScenarioInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::irp::ScenarioInfo, scenario_id_),
  PROTOBUF_FIELD_OFFSET(::irp::ScenarioInfo, daily_demands_),
  PROTOBUF_FIELD_OFFSET(::irp::ScenarioInfo, daily_delivery_costs_),
  PROTOBUF_FIELD_OFFSET(::irp::ScenarioInfo, daily_capa_penalty_costs_),
  PROTOBUF_FIELD_OFFSET(::irp::ScenarioInfo, day_1_cost_),
  PROTOBUF_FIELD_OFFSET(::irp::ScenarioInfo, total_cost_),
  PROTOBUF_FIELD_OFFSET(::irp::ScenarioInfo, daily_plans_),
  PROTOBUF_FIELD_OFFSET(::irp::ScenarioInfo, daily_quantities_),
  PROTOBUF_FIELD_OFFSET(::irp::ScenarioInfo, start_inventory_),
  PROTOBUF_FIELD_OFFSET(::irp::ScenarioInfo, actual_day_1_delivery_),
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  0,
  ~0u,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::irp::OuReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::irp::OuReq, client_id_),
  PROTOBUF_FIELD_OFFSET(::irp::OuReq, nb_days_),
  PROTOBUF_FIELD_OFFSET(::irp::OuReq, nb_scenario_),
  PROTOBUF_FIELD_OFFSET(::irp::OuReq, max_inventory_),
  PROTOBUF_FIELD_OFFSET(::irp::OuReq, start_inventory_),
  PROTOBUF_FIELD_OFFSET(::irp::OuReq, inventory_cost_),
  PROTOBUF_FIELD_OFFSET(::irp::OuReq, stockout_cost_),
  PROTOBUF_FIELD_OFFSET(::irp::OuReq, supplier_minus_cost_),
  PROTOBUF_FIELD_OFFSET(::irp::OuReq, control_day_1_),
  PROTOBUF_FIELD_OFFSET(::irp::OuReq, control_day_1_info_),
  PROTOBUF_FIELD_OFFSET(::irp::OuReq, scenario_infos_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::irp::OuResp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::irp::OuResp, scenario_info_results_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::irp::CapaCostFunc)},
  { 9, -1, sizeof(::irp::ControlDayOne)},
  { 16, 31, sizeof(::irp::ScenarioInfo)},
  { 41, -1, sizeof(::irp::OuReq)},
  { 57, -1, sizeof(::irp::OuResp)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::irp::_CapaCostFunc_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::irp::_ControlDayOne_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::irp::_ScenarioInfo_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::irp::_OuReq_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::irp::_OuResp_default_instance_),
};

const char descriptor_table_protodef_irp_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\tirp.proto\022\003irp\"Q\n\014CapaCostFunc\022\021\n\tthre"
  "shold\030\001 \001(\001\022\014\n\004cost\030\002 \001(\001\022\r\n\005slope\030\003 \001(\001"
  "\022\021\n\tintercept\030\004 \001(\001\";\n\rControlDayOne\022\026\n\016"
  "day_1_delivery\030\001 \001(\010\022\022\n\nday_1_cost\030\002 \001(\001"
  "\"\265\002\n\014ScenarioInfo\022\023\n\013scenario_id\030\001 \001(\005\022\025"
  "\n\rdaily_demands\030\002 \003(\001\022\034\n\024daily_delivery_"
  "costs\030\003 \003(\001\0223\n\030daily_capa_penalty_costs\030"
  "\004 \003(\0132\021.irp.CapaCostFunc\022\022\n\nday_1_cost\030\005"
  " \001(\001\022\022\n\ntotal_cost\030\006 \001(\001\022\023\n\013daily_plans\030"
  "\007 \003(\010\022\030\n\020daily_quantities\030\010 \003(\001\022\034\n\017start"
  "_inventory\030\t \001(\005H\000\210\001\001\022\035\n\025actual_day_1_de"
  "livery\030\n \001(\010B\022\n\020_start_inventory\"\256\002\n\005OuR"
  "eq\022\021\n\tclient_id\030\001 \001(\005\022\017\n\007nb_days\030\002 \001(\005\022\023"
  "\n\013nb_scenario\030\003 \001(\005\022\025\n\rmax_inventory\030\004 \001"
  "(\005\022\027\n\017start_inventory\030\005 \001(\005\022\026\n\016inventory"
  "_cost\030\006 \001(\001\022\025\n\rstockout_cost\030\007 \001(\001\022\033\n\023su"
  "pplier_minus_cost\030\010 \001(\001\022\025\n\rcontrol_day_1"
  "\030\t \001(\005\022.\n\022control_day_1_info\030\n \001(\0132\022.irp"
  ".ControlDayOne\022)\n\016scenario_infos\030\013 \003(\0132\021"
  ".irp.ScenarioInfo\":\n\006OuResp\0220\n\025scenario_"
  "info_results\030\001 \003(\0132\021.irp.ScenarioInfo2<\n"
  "\nIrpService\022.\n\023ProcessOptimization\022\n.irp"
  ".OuReq\032\013.irp.OuRespb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_irp_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_irp_2eproto_sccs[5] = {
  &scc_info_CapaCostFunc_irp_2eproto.base,
  &scc_info_ControlDayOne_irp_2eproto.base,
  &scc_info_OuReq_irp_2eproto.base,
  &scc_info_OuResp_irp_2eproto.base,
  &scc_info_ScenarioInfo_irp_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_irp_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_irp_2eproto = {
  false, false, descriptor_table_protodef_irp_2eproto, "irp.proto", 907,
  &descriptor_table_irp_2eproto_once, descriptor_table_irp_2eproto_sccs, descriptor_table_irp_2eproto_deps, 5, 0,
  schemas, file_default_instances, TableStruct_irp_2eproto::offsets,
  file_level_metadata_irp_2eproto, 5, file_level_enum_descriptors_irp_2eproto, file_level_service_descriptors_irp_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_irp_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_irp_2eproto)), true);
namespace irp {

// ===================================================================

void CapaCostFunc::InitAsDefaultInstance() {
}
class CapaCostFunc::_Internal {
 public:
};

CapaCostFunc::CapaCostFunc(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:irp.CapaCostFunc)
}
CapaCostFunc::CapaCostFunc(const CapaCostFunc& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&threshold_, &from.threshold_,
    static_cast<size_t>(reinterpret_cast<char*>(&intercept_) -
    reinterpret_cast<char*>(&threshold_)) + sizeof(intercept_));
  // @@protoc_insertion_point(copy_constructor:irp.CapaCostFunc)
}

void CapaCostFunc::SharedCtor() {
  ::memset(&threshold_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&intercept_) -
      reinterpret_cast<char*>(&threshold_)) + sizeof(intercept_));
}

CapaCostFunc::~CapaCostFunc() {
  // @@protoc_insertion_point(destructor:irp.CapaCostFunc)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void CapaCostFunc::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void CapaCostFunc::ArenaDtor(void* object) {
  CapaCostFunc* _this = reinterpret_cast< CapaCostFunc* >(object);
  (void)_this;
}
void CapaCostFunc::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void CapaCostFunc::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CapaCostFunc& CapaCostFunc::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_CapaCostFunc_irp_2eproto.base);
  return *internal_default_instance();
}


void CapaCostFunc::Clear() {
// @@protoc_insertion_point(message_clear_start:irp.CapaCostFunc)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&threshold_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&intercept_) -
      reinterpret_cast<char*>(&threshold_)) + sizeof(intercept_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CapaCostFunc::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // double threshold = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 9)) {
          threshold_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double cost = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 17)) {
          cost_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double slope = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 25)) {
          slope_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double intercept = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 33)) {
          intercept_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* CapaCostFunc::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:irp.CapaCostFunc)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double threshold = 1;
  if (!(this->threshold() <= 0 && this->threshold() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(1, this->_internal_threshold(), target);
  }

  // double cost = 2;
  if (!(this->cost() <= 0 && this->cost() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(2, this->_internal_cost(), target);
  }

  // double slope = 3;
  if (!(this->slope() <= 0 && this->slope() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(3, this->_internal_slope(), target);
  }

  // double intercept = 4;
  if (!(this->intercept() <= 0 && this->intercept() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(4, this->_internal_intercept(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:irp.CapaCostFunc)
  return target;
}

size_t CapaCostFunc::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:irp.CapaCostFunc)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double threshold = 1;
  if (!(this->threshold() <= 0 && this->threshold() >= 0)) {
    total_size += 1 + 8;
  }

  // double cost = 2;
  if (!(this->cost() <= 0 && this->cost() >= 0)) {
    total_size += 1 + 8;
  }

  // double slope = 3;
  if (!(this->slope() <= 0 && this->slope() >= 0)) {
    total_size += 1 + 8;
  }

  // double intercept = 4;
  if (!(this->intercept() <= 0 && this->intercept() >= 0)) {
    total_size += 1 + 8;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CapaCostFunc::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:irp.CapaCostFunc)
  GOOGLE_DCHECK_NE(&from, this);
  const CapaCostFunc* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CapaCostFunc>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:irp.CapaCostFunc)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:irp.CapaCostFunc)
    MergeFrom(*source);
  }
}

void CapaCostFunc::MergeFrom(const CapaCostFunc& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:irp.CapaCostFunc)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from.threshold() <= 0 && from.threshold() >= 0)) {
    _internal_set_threshold(from._internal_threshold());
  }
  if (!(from.cost() <= 0 && from.cost() >= 0)) {
    _internal_set_cost(from._internal_cost());
  }
  if (!(from.slope() <= 0 && from.slope() >= 0)) {
    _internal_set_slope(from._internal_slope());
  }
  if (!(from.intercept() <= 0 && from.intercept() >= 0)) {
    _internal_set_intercept(from._internal_intercept());
  }
}

void CapaCostFunc::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:irp.CapaCostFunc)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CapaCostFunc::CopyFrom(const CapaCostFunc& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:irp.CapaCostFunc)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CapaCostFunc::IsInitialized() const {
  return true;
}

void CapaCostFunc::InternalSwap(CapaCostFunc* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CapaCostFunc, intercept_)
      + sizeof(CapaCostFunc::intercept_)
      - PROTOBUF_FIELD_OFFSET(CapaCostFunc, threshold_)>(
          reinterpret_cast<char*>(&threshold_),
          reinterpret_cast<char*>(&other->threshold_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CapaCostFunc::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ControlDayOne::InitAsDefaultInstance() {
}
class ControlDayOne::_Internal {
 public:
};

ControlDayOne::ControlDayOne(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:irp.ControlDayOne)
}
ControlDayOne::ControlDayOne(const ControlDayOne& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&day_1_cost_, &from.day_1_cost_,
    static_cast<size_t>(reinterpret_cast<char*>(&day_1_delivery_) -
    reinterpret_cast<char*>(&day_1_cost_)) + sizeof(day_1_delivery_));
  // @@protoc_insertion_point(copy_constructor:irp.ControlDayOne)
}

void ControlDayOne::SharedCtor() {
  ::memset(&day_1_cost_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&day_1_delivery_) -
      reinterpret_cast<char*>(&day_1_cost_)) + sizeof(day_1_delivery_));
}

ControlDayOne::~ControlDayOne() {
  // @@protoc_insertion_point(destructor:irp.ControlDayOne)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ControlDayOne::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ControlDayOne::ArenaDtor(void* object) {
  ControlDayOne* _this = reinterpret_cast< ControlDayOne* >(object);
  (void)_this;
}
void ControlDayOne::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ControlDayOne::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ControlDayOne& ControlDayOne::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ControlDayOne_irp_2eproto.base);
  return *internal_default_instance();
}


void ControlDayOne::Clear() {
// @@protoc_insertion_point(message_clear_start:irp.ControlDayOne)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&day_1_cost_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&day_1_delivery_) -
      reinterpret_cast<char*>(&day_1_cost_)) + sizeof(day_1_delivery_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ControlDayOne::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bool day_1_delivery = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          day_1_delivery_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double day_1_cost = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 17)) {
          day_1_cost_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ControlDayOne::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:irp.ControlDayOne)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool day_1_delivery = 1;
  if (this->day_1_delivery() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_day_1_delivery(), target);
  }

  // double day_1_cost = 2;
  if (!(this->day_1_cost() <= 0 && this->day_1_cost() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(2, this->_internal_day_1_cost(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:irp.ControlDayOne)
  return target;
}

size_t ControlDayOne::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:irp.ControlDayOne)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double day_1_cost = 2;
  if (!(this->day_1_cost() <= 0 && this->day_1_cost() >= 0)) {
    total_size += 1 + 8;
  }

  // bool day_1_delivery = 1;
  if (this->day_1_delivery() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ControlDayOne::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:irp.ControlDayOne)
  GOOGLE_DCHECK_NE(&from, this);
  const ControlDayOne* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ControlDayOne>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:irp.ControlDayOne)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:irp.ControlDayOne)
    MergeFrom(*source);
  }
}

void ControlDayOne::MergeFrom(const ControlDayOne& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:irp.ControlDayOne)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from.day_1_cost() <= 0 && from.day_1_cost() >= 0)) {
    _internal_set_day_1_cost(from._internal_day_1_cost());
  }
  if (from.day_1_delivery() != 0) {
    _internal_set_day_1_delivery(from._internal_day_1_delivery());
  }
}

void ControlDayOne::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:irp.ControlDayOne)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ControlDayOne::CopyFrom(const ControlDayOne& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:irp.ControlDayOne)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ControlDayOne::IsInitialized() const {
  return true;
}

void ControlDayOne::InternalSwap(ControlDayOne* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ControlDayOne, day_1_delivery_)
      + sizeof(ControlDayOne::day_1_delivery_)
      - PROTOBUF_FIELD_OFFSET(ControlDayOne, day_1_cost_)>(
          reinterpret_cast<char*>(&day_1_cost_),
          reinterpret_cast<char*>(&other->day_1_cost_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ControlDayOne::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ScenarioInfo::InitAsDefaultInstance() {
}
class ScenarioInfo::_Internal {
 public:
  using HasBits = decltype(std::declval<ScenarioInfo>()._has_bits_);
  static void set_has_start_inventory(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

ScenarioInfo::ScenarioInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  daily_demands_(arena),
  daily_delivery_costs_(arena),
  daily_capa_penalty_costs_(arena),
  daily_plans_(arena),
  daily_quantities_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:irp.ScenarioInfo)
}
ScenarioInfo::ScenarioInfo(const ScenarioInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_),
      daily_demands_(from.daily_demands_),
      daily_delivery_costs_(from.daily_delivery_costs_),
      daily_capa_penalty_costs_(from.daily_capa_penalty_costs_),
      daily_plans_(from.daily_plans_),
      daily_quantities_(from.daily_quantities_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&day_1_cost_, &from.day_1_cost_,
    static_cast<size_t>(reinterpret_cast<char*>(&actual_day_1_delivery_) -
    reinterpret_cast<char*>(&day_1_cost_)) + sizeof(actual_day_1_delivery_));
  // @@protoc_insertion_point(copy_constructor:irp.ScenarioInfo)
}

void ScenarioInfo::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ScenarioInfo_irp_2eproto.base);
  ::memset(&day_1_cost_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&actual_day_1_delivery_) -
      reinterpret_cast<char*>(&day_1_cost_)) + sizeof(actual_day_1_delivery_));
}

ScenarioInfo::~ScenarioInfo() {
  // @@protoc_insertion_point(destructor:irp.ScenarioInfo)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ScenarioInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ScenarioInfo::ArenaDtor(void* object) {
  ScenarioInfo* _this = reinterpret_cast< ScenarioInfo* >(object);
  (void)_this;
}
void ScenarioInfo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ScenarioInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ScenarioInfo& ScenarioInfo::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ScenarioInfo_irp_2eproto.base);
  return *internal_default_instance();
}


void ScenarioInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:irp.ScenarioInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  daily_demands_.Clear();
  daily_delivery_costs_.Clear();
  daily_capa_penalty_costs_.Clear();
  daily_plans_.Clear();
  daily_quantities_.Clear();
  ::memset(&day_1_cost_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&scenario_id_) -
      reinterpret_cast<char*>(&day_1_cost_)) + sizeof(scenario_id_));
  start_inventory_ = 0;
  ::memset(&total_cost_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&actual_day_1_delivery_) -
      reinterpret_cast<char*>(&total_cost_)) + sizeof(actual_day_1_delivery_));
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ScenarioInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 scenario_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          scenario_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated double daily_demands = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_daily_demands(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 17) {
          _internal_add_daily_demands(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // repeated double daily_delivery_costs = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_daily_delivery_costs(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 25) {
          _internal_add_daily_delivery_costs(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // repeated .irp.CapaCostFunc daily_capa_penalty_costs = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_daily_capa_penalty_costs(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else goto handle_unusual;
        continue;
      // double day_1_cost = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 41)) {
          day_1_cost_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double total_cost = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 49)) {
          total_cost_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // repeated bool daily_plans = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedBoolParser(_internal_mutable_daily_plans(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56) {
          _internal_add_daily_plans(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated double daily_quantities = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_daily_quantities(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 65) {
          _internal_add_daily_quantities(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // int32 start_inventory = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 72)) {
          _Internal::set_has_start_inventory(&has_bits);
          start_inventory_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool actual_day_1_delivery = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 80)) {
          actual_day_1_delivery_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ScenarioInfo::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:irp.ScenarioInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 scenario_id = 1;
  if (this->scenario_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_scenario_id(), target);
  }

  // repeated double daily_demands = 2;
  if (this->_internal_daily_demands_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_daily_demands(), target);
  }

  // repeated double daily_delivery_costs = 3;
  if (this->_internal_daily_delivery_costs_size() > 0) {
    target = stream->WriteFixedPacked(3, _internal_daily_delivery_costs(), target);
  }

  // repeated .irp.CapaCostFunc daily_capa_penalty_costs = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_daily_capa_penalty_costs_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, this->_internal_daily_capa_penalty_costs(i), target, stream);
  }

  // double day_1_cost = 5;
  if (!(this->day_1_cost() <= 0 && this->day_1_cost() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(5, this->_internal_day_1_cost(), target);
  }

  // double total_cost = 6;
  if (!(this->total_cost() <= 0 && this->total_cost() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(6, this->_internal_total_cost(), target);
  }

  // repeated bool daily_plans = 7;
  if (this->_internal_daily_plans_size() > 0) {
    target = stream->WriteFixedPacked(7, _internal_daily_plans(), target);
  }

  // repeated double daily_quantities = 8;
  if (this->_internal_daily_quantities_size() > 0) {
    target = stream->WriteFixedPacked(8, _internal_daily_quantities(), target);
  }

  // int32 start_inventory = 9;
  if (_internal_has_start_inventory()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(9, this->_internal_start_inventory(), target);
  }

  // bool actual_day_1_delivery = 10;
  if (this->actual_day_1_delivery() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(10, this->_internal_actual_day_1_delivery(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:irp.ScenarioInfo)
  return target;
}

size_t ScenarioInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:irp.ScenarioInfo)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double daily_demands = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_daily_demands_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _daily_demands_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated double daily_delivery_costs = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_daily_delivery_costs_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _daily_delivery_costs_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated .irp.CapaCostFunc daily_capa_penalty_costs = 4;
  total_size += 1UL * this->_internal_daily_capa_penalty_costs_size();
  for (const auto& msg : this->daily_capa_penalty_costs_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated bool daily_plans = 7;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_daily_plans_size());
    size_t data_size = 1UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _daily_plans_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated double daily_quantities = 8;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_daily_quantities_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _daily_quantities_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // double day_1_cost = 5;
  if (!(this->day_1_cost() <= 0 && this->day_1_cost() >= 0)) {
    total_size += 1 + 8;
  }

  // int32 scenario_id = 1;
  if (this->scenario_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_scenario_id());
  }

  // int32 start_inventory = 9;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_start_inventory());
  }

  // double total_cost = 6;
  if (!(this->total_cost() <= 0 && this->total_cost() >= 0)) {
    total_size += 1 + 8;
  }

  // bool actual_day_1_delivery = 10;
  if (this->actual_day_1_delivery() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ScenarioInfo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:irp.ScenarioInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const ScenarioInfo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ScenarioInfo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:irp.ScenarioInfo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:irp.ScenarioInfo)
    MergeFrom(*source);
  }
}

void ScenarioInfo::MergeFrom(const ScenarioInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:irp.ScenarioInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  daily_demands_.MergeFrom(from.daily_demands_);
  daily_delivery_costs_.MergeFrom(from.daily_delivery_costs_);
  daily_capa_penalty_costs_.MergeFrom(from.daily_capa_penalty_costs_);
  daily_plans_.MergeFrom(from.daily_plans_);
  daily_quantities_.MergeFrom(from.daily_quantities_);
  if (!(from.day_1_cost() <= 0 && from.day_1_cost() >= 0)) {
    _internal_set_day_1_cost(from._internal_day_1_cost());
  }
  if (from.scenario_id() != 0) {
    _internal_set_scenario_id(from._internal_scenario_id());
  }
  if (from._internal_has_start_inventory()) {
    _internal_set_start_inventory(from._internal_start_inventory());
  }
  if (!(from.total_cost() <= 0 && from.total_cost() >= 0)) {
    _internal_set_total_cost(from._internal_total_cost());
  }
  if (from.actual_day_1_delivery() != 0) {
    _internal_set_actual_day_1_delivery(from._internal_actual_day_1_delivery());
  }
}

void ScenarioInfo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:irp.ScenarioInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ScenarioInfo::CopyFrom(const ScenarioInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:irp.ScenarioInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ScenarioInfo::IsInitialized() const {
  return true;
}

void ScenarioInfo::InternalSwap(ScenarioInfo* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  daily_demands_.InternalSwap(&other->daily_demands_);
  daily_delivery_costs_.InternalSwap(&other->daily_delivery_costs_);
  daily_capa_penalty_costs_.InternalSwap(&other->daily_capa_penalty_costs_);
  daily_plans_.InternalSwap(&other->daily_plans_);
  daily_quantities_.InternalSwap(&other->daily_quantities_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ScenarioInfo, actual_day_1_delivery_)
      + sizeof(ScenarioInfo::actual_day_1_delivery_)
      - PROTOBUF_FIELD_OFFSET(ScenarioInfo, day_1_cost_)>(
          reinterpret_cast<char*>(&day_1_cost_),
          reinterpret_cast<char*>(&other->day_1_cost_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ScenarioInfo::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void OuReq::InitAsDefaultInstance() {
  ::irp::_OuReq_default_instance_._instance.get_mutable()->control_day_1_info_ = const_cast< ::irp::ControlDayOne*>(
      ::irp::ControlDayOne::internal_default_instance());
}
class OuReq::_Internal {
 public:
  static const ::irp::ControlDayOne& control_day_1_info(const OuReq* msg);
};

const ::irp::ControlDayOne&
OuReq::_Internal::control_day_1_info(const OuReq* msg) {
  return *msg->control_day_1_info_;
}
OuReq::OuReq(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  scenario_infos_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:irp.OuReq)
}
OuReq::OuReq(const OuReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      scenario_infos_(from.scenario_infos_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_control_day_1_info()) {
    control_day_1_info_ = new ::irp::ControlDayOne(*from.control_day_1_info_);
  } else {
    control_day_1_info_ = nullptr;
  }
  ::memcpy(&client_id_, &from.client_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&supplier_minus_cost_) -
    reinterpret_cast<char*>(&client_id_)) + sizeof(supplier_minus_cost_));
  // @@protoc_insertion_point(copy_constructor:irp.OuReq)
}

void OuReq::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_OuReq_irp_2eproto.base);
  ::memset(&control_day_1_info_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&supplier_minus_cost_) -
      reinterpret_cast<char*>(&control_day_1_info_)) + sizeof(supplier_minus_cost_));
}

OuReq::~OuReq() {
  // @@protoc_insertion_point(destructor:irp.OuReq)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void OuReq::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete control_day_1_info_;
}

void OuReq::ArenaDtor(void* object) {
  OuReq* _this = reinterpret_cast< OuReq* >(object);
  (void)_this;
}
void OuReq::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void OuReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const OuReq& OuReq::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_OuReq_irp_2eproto.base);
  return *internal_default_instance();
}


void OuReq::Clear() {
// @@protoc_insertion_point(message_clear_start:irp.OuReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  scenario_infos_.Clear();
  if (GetArena() == nullptr && control_day_1_info_ != nullptr) {
    delete control_day_1_info_;
  }
  control_day_1_info_ = nullptr;
  ::memset(&client_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&supplier_minus_cost_) -
      reinterpret_cast<char*>(&client_id_)) + sizeof(supplier_minus_cost_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OuReq::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 client_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          client_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 nb_days = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          nb_days_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 nb_scenario = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          nb_scenario_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 max_inventory = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          max_inventory_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 start_inventory = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          start_inventory_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double inventory_cost = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 49)) {
          inventory_cost_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double stockout_cost = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 57)) {
          stockout_cost_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double supplier_minus_cost = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 65)) {
          supplier_minus_cost_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // int32 control_day_1 = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 72)) {
          control_day_1_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .irp.ControlDayOne control_day_1_info = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 82)) {
          ptr = ctx->ParseMessage(_internal_mutable_control_day_1_info(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .irp.ScenarioInfo scenario_infos = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 90)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_scenario_infos(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<90>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* OuReq::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:irp.OuReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 client_id = 1;
  if (this->client_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_client_id(), target);
  }

  // int32 nb_days = 2;
  if (this->nb_days() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_nb_days(), target);
  }

  // int32 nb_scenario = 3;
  if (this->nb_scenario() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_nb_scenario(), target);
  }

  // int32 max_inventory = 4;
  if (this->max_inventory() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(4, this->_internal_max_inventory(), target);
  }

  // int32 start_inventory = 5;
  if (this->start_inventory() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(5, this->_internal_start_inventory(), target);
  }

  // double inventory_cost = 6;
  if (!(this->inventory_cost() <= 0 && this->inventory_cost() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(6, this->_internal_inventory_cost(), target);
  }

  // double stockout_cost = 7;
  if (!(this->stockout_cost() <= 0 && this->stockout_cost() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(7, this->_internal_stockout_cost(), target);
  }

  // double supplier_minus_cost = 8;
  if (!(this->supplier_minus_cost() <= 0 && this->supplier_minus_cost() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(8, this->_internal_supplier_minus_cost(), target);
  }

  // int32 control_day_1 = 9;
  if (this->control_day_1() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(9, this->_internal_control_day_1(), target);
  }

  // .irp.ControlDayOne control_day_1_info = 10;
  if (this->has_control_day_1_info()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        10, _Internal::control_day_1_info(this), target, stream);
  }

  // repeated .irp.ScenarioInfo scenario_infos = 11;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_scenario_infos_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(11, this->_internal_scenario_infos(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:irp.OuReq)
  return target;
}

size_t OuReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:irp.OuReq)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .irp.ScenarioInfo scenario_infos = 11;
  total_size += 1UL * this->_internal_scenario_infos_size();
  for (const auto& msg : this->scenario_infos_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .irp.ControlDayOne control_day_1_info = 10;
  if (this->has_control_day_1_info()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *control_day_1_info_);
  }

  // int32 client_id = 1;
  if (this->client_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_client_id());
  }

  // int32 nb_days = 2;
  if (this->nb_days() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_nb_days());
  }

  // int32 nb_scenario = 3;
  if (this->nb_scenario() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_nb_scenario());
  }

  // int32 max_inventory = 4;
  if (this->max_inventory() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_max_inventory());
  }

  // double inventory_cost = 6;
  if (!(this->inventory_cost() <= 0 && this->inventory_cost() >= 0)) {
    total_size += 1 + 8;
  }

  // double stockout_cost = 7;
  if (!(this->stockout_cost() <= 0 && this->stockout_cost() >= 0)) {
    total_size += 1 + 8;
  }

  // int32 start_inventory = 5;
  if (this->start_inventory() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_start_inventory());
  }

  // int32 control_day_1 = 9;
  if (this->control_day_1() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_control_day_1());
  }

  // double supplier_minus_cost = 8;
  if (!(this->supplier_minus_cost() <= 0 && this->supplier_minus_cost() >= 0)) {
    total_size += 1 + 8;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void OuReq::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:irp.OuReq)
  GOOGLE_DCHECK_NE(&from, this);
  const OuReq* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<OuReq>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:irp.OuReq)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:irp.OuReq)
    MergeFrom(*source);
  }
}

void OuReq::MergeFrom(const OuReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:irp.OuReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  scenario_infos_.MergeFrom(from.scenario_infos_);
  if (from.has_control_day_1_info()) {
    _internal_mutable_control_day_1_info()->::irp::ControlDayOne::MergeFrom(from._internal_control_day_1_info());
  }
  if (from.client_id() != 0) {
    _internal_set_client_id(from._internal_client_id());
  }
  if (from.nb_days() != 0) {
    _internal_set_nb_days(from._internal_nb_days());
  }
  if (from.nb_scenario() != 0) {
    _internal_set_nb_scenario(from._internal_nb_scenario());
  }
  if (from.max_inventory() != 0) {
    _internal_set_max_inventory(from._internal_max_inventory());
  }
  if (!(from.inventory_cost() <= 0 && from.inventory_cost() >= 0)) {
    _internal_set_inventory_cost(from._internal_inventory_cost());
  }
  if (!(from.stockout_cost() <= 0 && from.stockout_cost() >= 0)) {
    _internal_set_stockout_cost(from._internal_stockout_cost());
  }
  if (from.start_inventory() != 0) {
    _internal_set_start_inventory(from._internal_start_inventory());
  }
  if (from.control_day_1() != 0) {
    _internal_set_control_day_1(from._internal_control_day_1());
  }
  if (!(from.supplier_minus_cost() <= 0 && from.supplier_minus_cost() >= 0)) {
    _internal_set_supplier_minus_cost(from._internal_supplier_minus_cost());
  }
}

void OuReq::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:irp.OuReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OuReq::CopyFrom(const OuReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:irp.OuReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OuReq::IsInitialized() const {
  return true;
}

void OuReq::InternalSwap(OuReq* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  scenario_infos_.InternalSwap(&other->scenario_infos_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(OuReq, supplier_minus_cost_)
      + sizeof(OuReq::supplier_minus_cost_)
      - PROTOBUF_FIELD_OFFSET(OuReq, control_day_1_info_)>(
          reinterpret_cast<char*>(&control_day_1_info_),
          reinterpret_cast<char*>(&other->control_day_1_info_));
}

::PROTOBUF_NAMESPACE_ID::Metadata OuReq::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void OuResp::InitAsDefaultInstance() {
}
class OuResp::_Internal {
 public:
};

OuResp::OuResp(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  scenario_info_results_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:irp.OuResp)
}
OuResp::OuResp(const OuResp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      scenario_info_results_(from.scenario_info_results_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:irp.OuResp)
}

void OuResp::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_OuResp_irp_2eproto.base);
}

OuResp::~OuResp() {
  // @@protoc_insertion_point(destructor:irp.OuResp)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void OuResp::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void OuResp::ArenaDtor(void* object) {
  OuResp* _this = reinterpret_cast< OuResp* >(object);
  (void)_this;
}
void OuResp::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void OuResp::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const OuResp& OuResp::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_OuResp_irp_2eproto.base);
  return *internal_default_instance();
}


void OuResp::Clear() {
// @@protoc_insertion_point(message_clear_start:irp.OuResp)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  scenario_info_results_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OuResp::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .irp.ScenarioInfo scenario_info_results = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_scenario_info_results(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* OuResp::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:irp.OuResp)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .irp.ScenarioInfo scenario_info_results = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_scenario_info_results_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_scenario_info_results(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:irp.OuResp)
  return target;
}

size_t OuResp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:irp.OuResp)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .irp.ScenarioInfo scenario_info_results = 1;
  total_size += 1UL * this->_internal_scenario_info_results_size();
  for (const auto& msg : this->scenario_info_results_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void OuResp::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:irp.OuResp)
  GOOGLE_DCHECK_NE(&from, this);
  const OuResp* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<OuResp>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:irp.OuResp)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:irp.OuResp)
    MergeFrom(*source);
  }
}

void OuResp::MergeFrom(const OuResp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:irp.OuResp)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  scenario_info_results_.MergeFrom(from.scenario_info_results_);
}

void OuResp::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:irp.OuResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OuResp::CopyFrom(const OuResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:irp.OuResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OuResp::IsInitialized() const {
  return true;
}

void OuResp::InternalSwap(OuResp* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  scenario_info_results_.InternalSwap(&other->scenario_info_results_);
}

::PROTOBUF_NAMESPACE_ID::Metadata OuResp::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace irp
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::irp::CapaCostFunc* Arena::CreateMaybeMessage< ::irp::CapaCostFunc >(Arena* arena) {
  return Arena::CreateMessageInternal< ::irp::CapaCostFunc >(arena);
}
template<> PROTOBUF_NOINLINE ::irp::ControlDayOne* Arena::CreateMaybeMessage< ::irp::ControlDayOne >(Arena* arena) {
  return Arena::CreateMessageInternal< ::irp::ControlDayOne >(arena);
}
template<> PROTOBUF_NOINLINE ::irp::ScenarioInfo* Arena::CreateMaybeMessage< ::irp::ScenarioInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::irp::ScenarioInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::irp::OuReq* Arena::CreateMaybeMessage< ::irp::OuReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::irp::OuReq >(arena);
}
template<> PROTOBUF_NOINLINE ::irp::OuResp* Arena::CreateMaybeMessage< ::irp::OuResp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::irp::OuResp >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
