# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: irp.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'irp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tirp.proto\x12\x03irp\"Q\n\x0c\x43\x61paCostFunc\x12\x11\n\tthreshold\x18\x01 \x01(\x01\x12\x0c\n\x04\x63ost\x18\x02 \x01(\x01\x12\r\n\x05slope\x18\x03 \x01(\x01\x12\x11\n\tintercept\x18\x04 \x01(\x01\";\n\rControlDayOne\x12\x16\n\x0e\x64\x61y_1_delivery\x18\x01 \x01(\x08\x12\x12\n\nday_1_cost\x18\x02 \x01(\x01\"\x96\x02\n\x0cScenarioInfo\x12\x13\n\x0bscenario_id\x18\x01 \x01(\x05\x12\x15\n\rdaily_demands\x18\x02 \x03(\x01\x12\x1c\n\x14\x64\x61ily_delivery_costs\x18\x03 \x03(\x01\x12\x33\n\x18\x64\x61ily_capa_penalty_costs\x18\x04 \x03(\x0b\x32\x11.irp.CapaCostFunc\x12\x12\n\nday_1_cost\x18\x05 \x01(\x01\x12\x12\n\ntotal_cost\x18\x06 \x01(\x01\x12\x13\n\x0b\x64\x61ily_plans\x18\x07 \x03(\x08\x12\x18\n\x10\x64\x61ily_quantities\x18\x08 \x03(\x01\x12\x1c\n\x0fstart_inventory\x18\t \x01(\x05H\x00\x88\x01\x01\x42\x12\n\x10_start_inventory\"\xae\x02\n\x05OuReq\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x0f\n\x07nb_days\x18\x02 \x01(\x05\x12\x13\n\x0bnb_scenario\x18\x03 \x01(\x05\x12\x15\n\rmax_inventory\x18\x04 \x01(\x05\x12\x17\n\x0fstart_inventory\x18\x05 \x01(\x05\x12\x16\n\x0einventory_cost\x18\x06 \x01(\x01\x12\x15\n\rstockout_cost\x18\x07 \x01(\x01\x12\x1b\n\x13supplier_minus_cost\x18\x08 \x01(\x01\x12\x15\n\rcontrol_day_1\x18\t \x01(\x05\x12.\n\x12\x63ontrol_day_1_info\x18\n \x01(\x0b\x32\x12.irp.ControlDayOne\x12)\n\x0escenario_infos\x18\x0b \x03(\x0b\x32\x11.irp.ScenarioInfo\":\n\x06OuResp\x12\x30\n\x15scenario_info_results\x18\x01 \x03(\x0b\x32\x11.irp.ScenarioInfo2<\n\nIrpService\x12.\n\x13ProcessOptimization\x12\n.irp.OuReq\x1a\x0b.irp.OuRespb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'irp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAPACOSTFUNC']._serialized_start=18
  _globals['_CAPACOSTFUNC']._serialized_end=99
  _globals['_CONTROLDAYONE']._serialized_start=101
  _globals['_CONTROLDAYONE']._serialized_end=160
  _globals['_SCENARIOINFO']._serialized_start=163
  _globals['_SCENARIOINFO']._serialized_end=441
  _globals['_OUREQ']._serialized_start=444
  _globals['_OUREQ']._serialized_end=746
  _globals['_OURESP']._serialized_start=748
  _globals['_OURESP']._serialized_end=806
  _globals['_IRPSERVICE']._serialized_start=808
  _globals['_IRPSERVICE']._serialized_end=868
# @@protoc_insertion_point(module_scope)
