# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import irp_pb2 as irp__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in irp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IrpServiceStub(object):
    """gRPC 服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessOptimization = channel.unary_unary(
                '/irp.IrpService/ProcessOptimization',
                request_serializer=irp__pb2.OuReq.SerializeToString,
                response_deserializer=irp__pb2.OuResp.FromString,
                _registered_method=True)


class IrpServiceServicer(object):
    """gRPC 服务定义
    """

    def ProcessOptimization(self, request, context):
        """处理优化请求
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IrpServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessOptimization': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessOptimization,
                    request_deserializer=irp__pb2.OuReq.FromString,
                    response_serializer=irp__pb2.OuResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'irp.IrpService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('irp.IrpService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IrpService(object):
    """gRPC 服务定义
    """

    @staticmethod
    def ProcessOptimization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/irp.IrpService/ProcessOptimization',
            irp__pb2.OuReq.SerializeToString,
            irp__pb2.OuResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
